#!/usr/bin/env bash
set -e

log() {
  echo "---> $*"
}

run() {
  echo "\$ $*"
  "$@"
}

build() {
  log 'building'
  run go generate $(glide novendor)
  run go build ./cmd/ddrop
}

serve() {
  build
  log 'starting server'
  run ./ddrop
}

tests() {
  log 'running tests'
  run go ./internal/...
  run ginkgo -r $(glide novendor)
}

watch() {
  log 'serving and watching for changes'
  (cd cmd/ddrop && fresh)
}

fatal() {
  echo "$0: $@"
  exit 1
}

main() {
  if [[ $# -lt 1 ]]; then
    fatal 'no arguments given'
  fi

  case "$1" in
    build) build ;;
    serve) serve ;;
    tests) tests ;;
    watch) watch ;;
    *) fatal "unknown command: $1" ;;
  esac
}

main "$@"
